# /etc/filebeat/filebeat.yml
# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html

# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-reloading.html#load-input-config
filebeat.config.inputs:
    enabled: true
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true
    reload.period: 10s
filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

# https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]

# https://www.elastic.co/guide/en/beats/filebeat/current/setup-kibana-endpoint.html
setup.kibana.host: "${KIBANA_HOST:http://kibana:5601}"

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# processors:
# - add_cloud_metadata: ~