global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: app-api 
    metrics_path: /prometheus
    static_configs:
      - targets: 
        - ${API_HOST}:${API_PORT}
        # - api:8080 # host.docker.internal:8080
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
        - rabbitmq:15692
  - job_name: telegraf
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
        - telegraf:9100
  - job_name: 'docker'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9323']