# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html
#-------------------------------- Redis Module --------------------------------
- module: redis
  # Main logs
  log:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/var/log/redis/redis.log*"]

  # Slow logs, retrieved via the Redis API (SLOWLOG)
  slowlog:
    enabled: true

    # The Redis hosts to connect to.
    var.hosts: ["${REDIS_HOST:redis}:${REDIS_PORT:6379}"]

    # Optional, the password to use when connecting to Redis.
    #var.password: