{
 "title": "API DASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"app-api\"}",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "go_goroutines ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"api:8080\"}",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "Response Time le",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_response_time_seconds_bucket{path!=\"/prometheus\", path!=\"/favicon.ico\"}",
     "legendFormat": "{{path}} {{method}} {{le}}"
    }
   ]
  },
  {
   "title": "Request count by URL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{path!=\"/prometheus\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Response count ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "http_response_time_seconds_count{path!=\"/prometheus\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Docker container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{API_VERSION=\"0.0.1\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker container mem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{API_VERSION=\"0.0.1\"}",
     "legendFormat": "{{container_name}} - {{API_VERSION}}"
    }
   ]
  },
  {
   "title": "Response code idelta1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "idelta(http_response_status_total{path!=\"/prometheus\"}[1m])",
     "legendFormat": "{{path}} {{method}} {{code}}"
    }
   ]
  }
 ]
}