version: '3.9'

services:

  nginx:
    container_name: nginx
    image: 'nginx:latest'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl-params.conf:/etc/nginx/ssl-params.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/keys/cert.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/keys/cert.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/keys/dhparam.pem:/etc/nginx/dhparam.pem
    networks:
      - netNginx

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3-management'
    ports:
     - 15672:15672
     - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASS:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 1
      start_period: 5s
    networks:
      - netApplication
    volumes:
      - ./rabbitmq/conf.d/:/etc/rabbitmq/conf.d/
      - rabbitmqData:/var/lib/rabbitmq/

  
  # setup MongoDB cluster for production
  mongo-replica-setup:
    container_name: mongo-setup
    image: 'mongo:latest'
    networks:
      - netApplication
    volumes:
      - ./mongodb/scripts/mongosetup.sh:/scripts/mongosetup.sh
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}

  mongo1:
    container_name: 'mongo1'
    image: 'mongo:latest'
    command:
      [
        "-f",
        "/etc/mongod.conf",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "${MONGO_REPLICA_SET_NAME}",
        "--bind_ip_all"
      ]
    ports:
      - 27017:27017
    networks:
      - netApplication
    volumes:
      - mongoData1:/data/db
      - mongoLog1:/var/log/mongodb
      - mongoConfig1:/data/configdb
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/file.key:/auth/file.key
      - ./mongodb/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: echo 'rs.status().ok' | mongosh admin -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 5s
      timeout: 10s
      retries: 1
      start_period: 5s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}

  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus:latest'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
    networks:
      - netApplication

  grafana:
    container_name: 'grafana'
    image: 'grafana/grafana:latest'
    volumes:
      - grafanaStorage:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
    networks:
      - netApplication

volumes:
  mongoData1:
  mongoLog1:
  mongoConfig1:
  rabbitmqData:
  grafanaStorage:


networks:
  netApplication:
    name: netApplication
  netNginx:
    name: netNginx
