version: '3.9'

services:
  api:
    container_name: api
    build:
      context: ../../../
      dockerfile: ./deployments/docker/api/Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_INITDB_NAME: ${MONGO_INITDB_NAME}
      RABBITMQ_URI: ${RABBITMQ_URI}
      RABBITMQ_EXCHANGE_TYPE: ${RABBITMQ_EXCHANGE_TYPE}
      RABBITMQ_EXCHANGE_REINDEX: ${RABBITMQ_EXCHANGE_REINDEX}
      RABBITMQ_ROUTING_PLACE_KEY: ${RABBITMQ_ROUTING_PLACE_KEY}
      RABBITMQ_QUEUE_PLACE_REINDEX: ${RABBITMQ_QUEUE_PLACE_REINDEX}
      RABBITMQ_CONSUMERS_PLACE_REINDEX_COUNT: ${RABBITMQ_CONSUMERS_PLACE_REINDEX_COUNT}
      RABBITMQ_CONSUMERS_PLACE_REINDEX_TAG: ${RABBITMQ_CONSUMERS_PLACE_REINDEX_TAG}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_PATH: ${SESSION_PATH}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      SESSION_MAX_AGE: ${SESSION_MAX_AGE}
      SESSION_DB_NAME: ${SESSION_DB_NAME}
      APP_VERSION: ${APP_VERSION}
      API_SCHEMA: ${API_SCHEMA}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      GIN_MODE: ${GIN_MODE}
      SITE_SCHEMA: ${SITE_SCHEMA}
      SITE_HOST: ${SITE_HOST}
      SITE_PORT: ${SITE_PORT}
      REDIS_URL: ${REDIS_URL}
    networks:
      - netApplication
      - netNginx
    external_links:
      - mongo1
      - rabbitmq
      - logstash
      - redis

networks:
  netApplication:
    name: netApplication
  netNginx:
    name: netNginx
