version: '3.9'

services:
  place_reindex_go_rabbitmq:
    container_name: place_reindex_go_rabbitmq
    build:
      context: ../../../../
      dockerfile: ./deployments/docker/consumers/place_reindex_go_rabbitmq/Dockerfile
    environment:
      APP_VERSION: ${APP_VERSION}
      API_SCHEMA: ${API_SCHEMA}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      GIN_MODE: ${GIN_MODE}
      MONGO_URI: ${MONGO_URI}
      MONGO_INITDB_NAME: ${MONGO_INITDB_NAME}
      RABBITMQ_URI: ${RABBITMQ_URI}
      RABBITMQ_EXCHANGE_TYPE: ${RABBITMQ_EXCHANGE_TYPE}
      RABBITMQ_EXCHANGE_REINDEX: ${RABBITMQ_EXCHANGE_REINDEX}
      RABBITMQ_ROUTING_PLACE_KEY: ${RABBITMQ_ROUTING_PLACE_KEY}
      RABBITMQ_QUEUE_PLACE_REINDEX: ${RABBITMQ_QUEUE_PLACE_REINDEX}
      RABBITMQ_CONSUMERS_PLACE_REINDEX_COUNT: ${RABBITMQ_CONSUMERS_PLACE_REINDEX_COUNT}
      RABBITMQ_CONSUMERS_PLACE_REINDEX_TAG: ${RABBITMQ_CONSUMERS_PLACE_REINDEX_TAG}
      SITE_SCHEMA: ${SITE_SCHEMA}
      SITE_HOST: ${SITE_HOST}
      SITE_PORT: ${SITE_PORT}
      REDIS_URL: ${REDIS_URL}
    networks:
      - netApplication
    external_links:
      - mongo1
      - rabbitmq
      - logstash

networks:
  netApplication:
    name: netApplication
