# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: check test and build
    runs-on: ubuntu-22.04
    env:
      GIN_MODE: release

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
        architecture: x64

    - name: Build
      run: make build

    - name: Test
      run: make test
